In [1]:
import sklearn
import pandas as pd
import numpy as np

df = pd.read_csv('train.csv')

In [2]:

y=df['satisfaction']


In [3]:
X = df.loc[:, df.columns != 'satisfaction']
X.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
l.fit(X[['Gender']])
df['Gender_res'] = l.transform(df[['Gender']])
df = df.drop('Gender', axis=1)

c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [5]:
l = LabelEncoder()
l.fit(X[['Type of Travel']])
df['Type of Travel_res'] = l.transform(df[['Type of Travel']])
df = df.drop('Type of Travel', axis=1)

c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [6]:

l = LabelEncoder()
l.fit(y)
df['satisfaction_res'] = l.transform(df[['satisfaction']])
df = df.drop('satisfaction', axis=1)
#df

c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [7]:
l.fit(X[['Customer Type']])
df['Customer Type_res'] = l.transform(df[['Customer Type']])
df = df.drop('Customer Type', axis=1)

c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [8]:
l.fit(X[['Class']])
df['Class_res'] = l.transform(df[['Class']])
df = df.drop('Class', axis=1)

c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [9]:
df = df.drop('id', axis=1)

In [10]:
y=df['satisfaction_res']
X_ = df.loc[:, df.columns != 'satisfaction_res']
X_.isnull().sum()



Unnamed: 0                             0
Age                                    0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
Gender_res                             0
Type of Travel_res                     0
Customer Type_res                      0
Class_res                              0
dtype: int64

In [11]:
X = X_.dropna(axis=1)
X.isnull().sum()

Unnamed: 0                           0
Age                                  0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Gender_res                           0
Type of Travel_res                   0
Customer Type_res                    0
Class_res                            0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler

X_train , X_test, y_train , y_test = train_test_split(X, y, test_size = 0.2)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

clf = DecisionTreeClassifier()
clf.fit(X_train , y_train)
y_predict = clf.predict(X_test)

print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.95


In [13]:
clf_tree = DecisionTreeClassifier(max_depth =22,min_samples_leaf = 3,
                            random_state = 0).fit(X_train, y_train)

print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf_tree.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf_tree.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 0.98
Accuracy of Decision Tree classifier on test set: 0.95


In [14]:
clf2 = DecisionTreeClassifier(max_depth = 10).fit(X_train_scaled, y_train)

print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf2.score(X_train_scaled, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf2.score(X_test_scaled, y_test)))

Accuracy of Decision Tree classifier on training set: 0.95
Accuracy of Decision Tree classifier on test set: 0.95


In [15]:
for i in range(1,17):
    clf2 = DecisionTreeClassifier(max_depth = i).fit(X_train, y_train)

    print('Accuracy of Decision Tree with depth ',i,' classifier on training set: {:.2f}'
     .format(clf2.score(X_train, y_train)))
    print('Accuracy of Decision Tree with depth ',i,' classifier on test set: {:.2f}'
     .format(clf2.score(X_test, y_test)))

Accuracy of Decision Tree with depth  1  classifier on training set: 0.79
Accuracy of Decision Tree with depth  1  classifier on test set: 0.79
Accuracy of Decision Tree with depth  2  classifier on training set: 0.86
Accuracy of Decision Tree with depth  2  classifier on test set: 0.86
Accuracy of Decision Tree with depth  3  classifier on training set: 0.88
Accuracy of Decision Tree with depth  3  classifier on test set: 0.89
Accuracy of Decision Tree with depth  4  classifier on training set: 0.89
Accuracy of Decision Tree with depth  4  classifier on test set: 0.89
Accuracy of Decision Tree with depth  5  classifier on training set: 0.91
Accuracy of Decision Tree with depth  5  classifier on test set: 0.91
Accuracy of Decision Tree with depth  6  classifier on training set: 0.92
Accuracy of Decision Tree with depth  6  classifier on test set: 0.92
Accuracy of Decision Tree with depth  7  classifier on training set: 0.93
Accuracy of Decision Tree with depth  7  classifier on test se

In [16]:
clf2.feature_importances_

array([0.00868001, 0.01275987, 0.01196757, 0.19080745, 0.002175  ,
       0.00164562, 0.02181135, 0.00200744, 0.38392382, 0.01429088,
       0.04993154, 0.00705835, 0.00823852, 0.0136766 , 0.02618708,
       0.01304212, 0.00721981, 0.00614875, 0.00070266, 0.15503798,
       0.04158095, 0.02110662])

In [17]:
from sklearn.dummy import DummyClassifier


dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)
y_dummy_predictions = dummy_majority.predict(X_test)
dummy_majority.score(X_test, y_test)


0.5656609402819883

In [18]:
from sklearn.metrics import confusion_matrix

confusion= confusion_matrix(y_test, y_dummy_predictions)

print('Most frequent class (dummy classifier)\n', confusion)

Most frequent class (dummy classifier)
 [[11755     0]
 [ 9026     0]]


In [19]:
dummy_classprop = DummyClassifier(strategy='stratified').fit(X_train, y_train)
y_classprop_predicted = dummy_classprop.predict(X_test)
confusion = confusion_matrix(y_test, y_classprop_predicted)

print('Random class-proportional prediction (dummy classifier)\n', confusion)

Random class-proportional prediction (dummy classifier)
 [[6696 5059]
 [5127 3899]]


In [20]:
tree_predicted = clf_tree.predict(X_test)
confusion = confusion_matrix(y_test, tree_predicted)

print('tree classifier\n ', confusion)

tree classifier
  [[11261   494]
 [  597  8429]]


In [21]:
from sklearn.linear_model import LogisticRegression

clf_LogisticRegression = LogisticRegression(solver='liblinear').fit(X_train,y_train)

In [22]:
y_predict = clf_LogisticRegression.predict(X_test)
y_predict

array([1, 1, 0, ..., 0, 0, 1])

In [23]:
y_predict_prob = clf_LogisticRegression.predict_proba(X_test)
y_predict_prob

array([[0.19262289, 0.80737711],
       [0.19316767, 0.80683233],
       [0.89312704, 0.10687296],
       ...,
       [0.55012734, 0.44987266],
       [0.55361898, 0.44638102],
       [0.20151736, 0.79848264]])

In [24]:
print('Accuracy of Logistic regression classifier on train set:' , clf_LogisticRegression.score(X_train, y_train))
print('Accuracy of Logistic regression classifier on test set:' , clf_LogisticRegression.score(X_test, y_test))

Accuracy of Logistic regression classifier on train set: 0.8438699276975085
Accuracy of Logistic regression classifier on test set: 0.8452913719262788


In [25]:

clf = LogisticRegression().fit(X_train_scaled, y_train)

print('Accuracy of Logistic regression classifier on test set:' , clf_LogisticRegression.score(X_train_scaled, y_train))
print('Accuracy of Logistic regression classifier on test set:' , clf_LogisticRegression.score(X_test_scaled, y_test))

Accuracy of Logistic regression classifier on test set: 0.82172202639462
Accuracy of Logistic regression classifier on test set: 0.824503151917617


c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [26]:
LogisticRegression_predicted = clf_LogisticRegression.predict(X_test)
confusion = confusion_matrix(y_test, LogisticRegression_predicted)

print('tree classifier\n ', confusion)

tree classifier
  [[10208  1547]
 [ 1668  7358]]


In [27]:
from sklearn.metrics import classification_report

print(classification_report(y_test, tree_predicted, target_names=['not 1', '1']))

              precision    recall  f1-score   support

       not 1       0.95      0.96      0.95     11755
           1       0.94      0.93      0.94      9026

    accuracy                           0.95     20781
   macro avg       0.95      0.95      0.95     20781
weighted avg       0.95      0.95      0.95     20781



In [28]:
from sklearn.metrics import classification_report

print(classification_report(y_test, LogisticRegression_predicted, target_names=['not 1', '1']))

              precision    recall  f1-score   support

       not 1       0.86      0.87      0.86     11755
           1       0.83      0.82      0.82      9026

    accuracy                           0.85     20781
   macro avg       0.84      0.84      0.84     20781
weighted avg       0.85      0.85      0.85     20781



In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score 
knn_classifier = KNeighborsClassifier(n_neighbors=19)


knn_classifier.fit(X_train, y_train)


y_knmpred = knn_classifier.predict(X_test)


accuracy = accuracy_score(y_test, y_knmpred)
print("Accuracy:", accuracy)

print('Accuracy of Logistic regression classifier on test set:' , knn_classifier.score(X_train, y_train))
print('Accuracy of Logistic regression classifier on test set:' , knn_classifier.score(X_test, y_test))

Accuracy: 0.6478032818439922
Accuracy of Logistic regression classifier on test set: 0.6721124117271995
Accuracy of Logistic regression classifier on test set: 0.6478032818439922


In [34]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=51)


knn_classifier.fit(X_train, y_train)

print('Accuracy of Logistic regression classifier on train set:' , knn_classifier.score(X_train, y_train))
print('Accuracy of Logistic regression classifier on test set:' , knn_classifier.score(X_test, y_test))

Accuracy of Logistic regression classifier on train set: 0.6653393164346811
Accuracy of Logistic regression classifier on test set: 0.6569462489774313


In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# Create a Naïve Bayes classifier
nb_classifier = GaussianNB()

# Train the classifier
nb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_nbpred = nb_classifier.predict(X_test)

# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_nbpred)
print("Accuracy:", accuracy)

Accuracy: 0.8178624705259612


In [35]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
gb_classifier = GradientBoostingClassifier()

# Train the classifier
gb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_gbpred = gb_classifier.predict(X_test)

# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_gbpred)
print("Accuracy:", accuracy)

Accuracy: 0.9433136037726769
